In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
d = np.zeros((2, 3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e = np.ones((3, 2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
f = np.arange(0, 10, 2)
print(f)

[0 2 4 6 8]


In [ ]:
g = np.linspace(0, 10, 5)  # 5 números de 0 a 10
print(g)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
h = np.random.random((2, 2))
print(h)

[[0.65270424 0.21355707]
 [0.74108702 0.78639425]]


In [ ]:
i = np.array([[1, 2, 3], [4, 5, 6]])
print(i[1, 2])

6


In [ ]:
j = np.array([1, 2, 3, 4, 5, 6])
print(j[j % 2 == 0])

[2 4 6]


In [ ]:
k = np.array([1, 2, 3])
l = np.array([4, 5, 6])
print(k + l)

[5 7 9]


In [ ]:
data = np.array([50, 80, 100, 120])
normalized_data = (data - data.min()) / (data.max() - data.min())
print(normalized_data)

[0.         0.42857143 0.71428571 1.        ]


In [ ]:
mean = data.mean()
std = data.std()
scaled_data = (data - mean) / std
print(scaled_data)

[-1.45010473 -0.29002095  0.48336824  1.25675744]


In [ ]:
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
solución = np.linalg.solve(A, b)
print(solución)


[2.2 3.6]


In [ ]:
normal_data = np.random.normal(0, 1, 1000)
print(normal_data)

[ 1.16870822e+00  1.37709516e+00  4.37308533e-02  1.13599110e+00
  4.73303880e-01 -8.19852955e-01  2.59913531e-02  1.10404943e+00
  4.37426991e-01 -4.59154200e-01 -1.85464536e+00 -5.23132550e-01
  1.02474553e+00  8.87459655e-02  3.06616561e-02  4.92851196e-01
 -1.21782873e+00 -3.77338368e-01  7.38863712e-01 -9.29741352e-01
  5.37347315e-01 -5.50470211e-01  3.07718491e-01 -1.59952430e+00
  9.82439992e-01 -3.61572244e-01 -2.01224018e-01 -2.60035637e-01
 -1.50045427e-03 -1.48396512e+00  1.12744758e+00  2.58105943e+00
 -7.98282585e-02  1.52358891e+00 -9.83668419e-02  1.12133332e-01
  1.19908388e+00  3.48698338e-01 -1.56937627e+00 -6.33905150e-01
  1.34871806e+00 -1.33916371e+00 -7.44683921e-01 -9.29645725e-02
  9.33621792e-01  5.19403239e-01  2.46204963e+00 -1.19041997e+00
  1.72972515e-02 -2.65520066e-02  1.25348687e-01 -2.22589852e+00
  4.82104797e-01  1.64169512e-01 -1.60446101e-01 -1.28264475e+00
 -8.61310079e-01 -9.51161839e-01 -5.91966298e-01  2.37495696e-01
  1.79913527e+00 -1.61853

In [ ]:
uniform_data = np.random.uniform(0, 1, 1000)
print(uniform_data)

[7.15061897e-01 3.64223308e-01 1.97917474e-01 3.39221091e-01
 6.74181596e-01 1.51556152e-01 9.09946239e-01 8.02703231e-01
 1.46010389e-01 8.27037358e-01 4.55472035e-01 9.60618626e-01
 6.16676582e-01 3.03757448e-01 8.86978697e-01 6.94674680e-01
 2.21136746e-01 2.47670611e-02 8.03012499e-01 4.96574950e-01
 8.14715841e-01 5.25399228e-01 6.23157700e-01 4.26816247e-01
 8.50515990e-01 6.86918384e-01 3.47200678e-01 3.44027295e-01
 5.93369895e-01 6.52473918e-01 1.07352629e-01 3.10834402e-01
 5.34487629e-01 5.97324800e-01 9.68652979e-01 3.81138466e-01
 6.87614970e-01 4.73479255e-01 9.20255771e-01 7.49005312e-01
 9.20942239e-01 8.32155506e-01 6.86746918e-01 2.07997449e-01
 9.07688721e-01 7.18709854e-01 8.12609574e-02 1.81154971e-01
 5.99281745e-01 2.25093371e-01 7.54480872e-01 6.19496614e-02
 1.92029580e-01 8.08903823e-01 2.25712992e-01 3.42061882e-01
 6.62111160e-02 8.94942303e-01 8.00269219e-01 8.81361445e-02
 1.40913658e-01 7.64608484e-01 4.29545946e-01 1.55274078e-01
 1.97255387e-01 5.972625